---

name: build-one
on:
  push:
    branches:
      - main
  schedule:
    - cron: '25 4 * * 4'

jobs:
  node-18-slim:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      node-docker-version: 18-slim
    secrets: inherit

  node-20-slim:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      node-docker-version: 20-slim
    secrets: inherit
